apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: trigger-argo-workflow
  title: Trigger Argo Workflow
  description: A template to trigger an Argo Workflow
spec:
  parameters:
    - title: Workflow Parameters
      properties:
        workflowTemplate:
          type: string
          title: Workflow Template
          description: Name of the Argo Workflow template
        namespace:
          type: string
          title: Namespace
          description: Namespace for the Argo Workflow
        parameters:
          type: object
          title: Parameters
          description: Parameters to pass to the workflow
  steps:
    - id: trigger-argo
      name: Trigger Argo Workflow
      action: argo:trigger-workflow
      input:
        workflowTemplate: ${{ parameters.workflowTemplate }}
        namespace: ${{ parameters.namespace }}
        parameters: ${{ parameters.parameters }}
  output:
    workflowName: ${{ steps.trigger-argo.output.workflowName }}